"""Care Package — the send-to-care-team artifact.

Doctrine:
- The server RENDERS; only the USER sends. We never SMTP, relay, or store
  PHI-adjacent PDFs. The share action is the device's native share sheet.
- Tamper gate: the client echoes back the report JSON + the report_sha256 it
  received. We re-parse, re-hash, and refuse to render a doctored report.
- Photos are optional (off by default) and MUST hash-match a view in the
  report — no attaching arbitrary images to a verified document.
"""
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.foot_check import FootCheckReport

PDF_DISCLAIMER = (
    "Patient-generated educational report. Not a clinical record. "
    "This tool never diagnoses. Generated by OpenDiabetic Foot Lab."
)


class CarePackageRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    report: FootCheckReport
    report_sha256: str = Field(min_length=64, max_length=64)
    include_photos: bool = False
    recipient_note: str = Field(default="", max_length=280)


class TamperError(ValueError):
    pass


def verify_report(req: CarePackageRequest) -> None:
    recomputed = req.report.report_sha256()
    if recomputed != req.report_sha256:
        raise TamperError(
            "Report hash mismatch — this report was modified after generation "
            "and cannot be rendered as a verified care package."
        )
